import React, { useState } from 'react';
import { ArrowRight, Check, Sparkles, User, Search, Cpu, Target, Eye, Send } from 'lucide-react';

interface StageInfo {
  id: string;
  num: string;
  label: string;
  headline: string;
  caption: string;
  uiBadge: string;
}

const WORKFLOW_STAGES: StageInfo[] = [
  {
    id: 'profile',
    num: '01',
    label: 'PROFILE',
    headline: 'Declare Verified Truth',
    caption: 'Declare your skills, experience ceiling, and availability. WorkMatch will never fabricate capabilities.',
    uiBadge: 'Profile Calibration'
  },
  {
    id: 'discover',
    num: '02',
    label: 'DISCOVER',
    headline: 'Multi-Channel Opportunity Ingestion',
    caption: 'Listings from Upwork, Fiverr, Freelancer, and direct feeds are normalized into a single structured stream.',
    uiBadge: 'Stream Normalization'
  },
  {
    id: 'analyze',
    num: '03',
    label: 'ANALYZE',
    headline: 'Structural Requirement Deconstruction',
    caption: 'Contracts are split into skills, complexity, budget, deadline, and communication expectations.',
    uiBadge: 'Tensor Deconstruction'
  },
  {
    id: 'match',
    num: '04',
    label: 'MATCH',
    headline: 'Multidimensional Mathematical Scoring',
    caption: 'Objective fit scores (0–100) are generated by comparing the contract against your profile tensor.',
    uiBadge: 'Match Engine Active'
  },
  {
    id: 'review',
    num: '05',
    label: 'REVIEW',
    headline: 'Transparent Explainability',
    caption: 'Inspect exactly why an opportunity fits—along with potential concerns like tight delivery windows.',
    uiBadge: 'Audit & Provenance'
  },
  {
    id: 'apply',
    num: '06',
    label: 'APPLY',
    headline: 'Human-Approved Proposal Dispatch',
    caption: 'Generate tailored proposals backed strictly by verified experience under your final review.',
    uiBadge: 'Proposal Studio'
  }
];

export const WorkflowJourneyTraveler: React.FC = () => {
  const [activeStageIdx, setActiveStageIdx] = useState<number>(0);
  const currentStage = WORKFLOW_STAGES[activeStageIdx];

  return (
    <div className="w-full max-w-5xl mx-auto my-8 select-none">
      <div className="rounded-3xl bg-[#0D1322] border-2 border-[#1B253B] shadow-2xl p-6 sm:p-9 relative overflow-hidden">
        {/* Header Stepper Navigation */}
        <div className="pb-6 border-b border-[#1B253B]">
          <div className="flex items-center justify-between mb-4">
            <span className="text-xs font-mono uppercase tracking-widest text-[#20D3C2] font-bold">
              THE COMPLETE WORKFLOW SEQUENCE
            </span>
            <span className="text-xs font-mono text-[#9AA8BC]">
              Stage {activeStageIdx + 1} of {WORKFLOW_STAGES.length}
            </span>
          </div>

          <div className="grid grid-cols-3 sm:grid-cols-6 gap-2">
            {WORKFLOW_STAGES.map((s, idx) => {
              const isActive = idx === activeStageIdx;
              return (
                <button
                  key={s.id}
                  onClick={() => setActiveStageIdx(idx)}
                  className={`py-2 px-2.5 rounded-xl text-xs font-mono transition-all text-center ${
                    isActive
                      ? 'bg-[#20D3C2] text-[#0B1220] font-bold shadow-glow-teal'
                      : 'bg-[#111A2E] text-[#9AA8BC] hover:text-[#F4F7FB] border border-[#1B253B]'
                  }`}
                >
                  <span className="block text-[10px] opacity-75">{s.num}</span>
                  <span className="truncate block">{s.label}</span>
                </button>
              );
            })}
          </div>
        </div>

        {/* Dynamic Stage Interface Display */}
        <div className="py-8 grid grid-cols-1 md:grid-cols-12 gap-8 items-center">
          {/* Left Column: Stage Narrative & Proof */}
          <div className="md:col-span-5 space-y-4">
            <span className="text-xs font-mono text-[#20D3C2] font-bold uppercase tracking-wider block">
              STAGE {currentStage.num} · {currentStage.label}
            </span>

            <h4 className="text-2xl sm:text-3xl font-bold text-[#F4F7FB] font-display">
              {currentStage.headline}
            </h4>

            <p className="text-sm text-[#9AA8BC] leading-relaxed">
              {currentStage.caption}
            </p>

            <div className="pt-2">
              <span className="inline-flex items-center gap-2 px-3 py-1.5 rounded-xl bg-[#111A2E] border border-[#20D3C2]/30 text-xs font-mono text-[#20D3C2] font-semibold">
                <Sparkles className="w-3.5 h-3.5" />
                <span>{currentStage.uiBadge}</span>
              </span>
            </div>
          </div>

          {/* Right Column: Miniature Real Product Interface */}
          <div className="md:col-span-7 rounded-2xl bg-[#111A2E] border-2 border-[#1B253B] p-5 shadow-xl space-y-3 min-h-[260px] flex flex-col justify-between">
            <div className="flex items-center justify-between pb-3 border-b border-[#1B253B] text-xs font-mono">
              <span className="text-[#F4F7FB] font-bold">WorkMatch System Node</span>
              <span className="text-[#20D3C2]">{currentStage.label} ACTIVE</span>
            </div>

            {/* Stage-specific miniature visual preview */}
            {currentStage.id === 'profile' && (
              <div className="space-y-2 text-xs font-mono">
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] flex justify-between">
                  <span>Declared Stack:</span>
                  <span className="text-[#20D3C2] font-bold">React 18 · TypeScript · Vite</span>
                </div>
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] flex justify-between">
                  <span>Weekly Window:</span>
                  <span className="text-[#35D07F] font-bold">20 Open Hours</span>
                </div>
              </div>
            )}

            {currentStage.id === 'discover' && (
              <div className="space-y-2 text-xs font-mono">
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] flex justify-between">
                  <span>Ingested Channels:</span>
                  <span className="text-[#20D3C2] font-bold">Upwork, Fiverr, Direct</span>
                </div>
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] flex justify-between">
                  <span>Deduplication:</span>
                  <span className="text-[#35D07F] font-bold">100% Unique Listings</span>
                </div>
              </div>
            )}

            {currentStage.id === 'analyze' && (
              <div className="space-y-2 text-xs font-mono">
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] flex justify-between">
                  <span>Deconstructed Dimensions:</span>
                  <span className="text-[#20D3C2] font-bold">8 Structural Layers</span>
                </div>
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] flex justify-between">
                  <span>Client Trust Verification:</span>
                  <span className="text-[#35D07F] font-bold">Escrow Verified</span>
                </div>
              </div>
            )}

            {currentStage.id === 'match' && (
              <div className="space-y-2 text-xs font-mono">
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] flex justify-between items-center">
                  <span>Multidimensional Fit:</span>
                  <span className="text-xl font-bold font-mono text-[#20D3C2]">97% MATCH</span>
                </div>
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] flex justify-between">
                  <span>Filtering Confidence:</span>
                  <span className="text-[#35D07F] font-bold">High Precision</span>
                </div>
              </div>
            )}

            {currentStage.id === 'review' && (
              <div className="space-y-2 text-xs font-mono">
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] text-[#35D07F]">
                  ✓ Verified Skills (React 18 &amp; TypeScript)
                </div>
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] text-[#F5B942]">
                  ⚠ Fast 12-day deadline flagged for attention
                </div>
              </div>
            )}

            {currentStage.id === 'apply' && (
              <div className="space-y-2 text-xs font-mono">
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] flex justify-between">
                  <span>Tailored Proposal Draft:</span>
                  <span className="text-[#20D3C2] font-bold">Ready for Review</span>
                </div>
                <div className="p-3 rounded-xl bg-[#070A12] border border-[#1B253B] flex justify-between">
                  <span>Claim Verification:</span>
                  <span className="text-[#35D07F] font-bold">100% Truthful Facts</span>
                </div>
              </div>
            )}

            <div className="pt-3 border-t border-[#1B253B] flex items-center justify-between">
              <button
                onClick={() => setActiveStageIdx(prev => Math.max(0, prev - 1))}
                disabled={activeStageIdx === 0}
                className="text-xs font-mono text-[#9AA8BC] hover:text-[#F4F7FB] disabled:opacity-30"
              >
                ← Prev
              </button>
              <button
                onClick={() => setActiveStageIdx(prev => Math.min(WORKFLOW_STAGES.length - 1, prev + 1))}
                disabled={activeStageIdx === WORKFLOW_STAGES.length - 1}
                className="text-xs font-mono text-[#20D3C2] hover:text-[#5EE7DF] font-bold flex items-center gap-1"
              >
                <span>Next Stage</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
